### ISSUE TITLE
Unable to start a personal version of philomena

### ISSUE THREAD

**Issue by Silentmatten** [philomena-dev/philomena#150]
i've been attempting to start a version of this software and it keeps crashing at the same spot each time. 

i'll admit i'm very new to this kind of stuff but i believe i was able to increase the amount of ram allocated to my WSL so i'm unaware if the issue i'm having is related to that or not. Was hoping posting the log here would help point out where i'm inputting something wrong.
[log.txt](https://github.com/philomena-dev/philomena/files/7720803/log.txt)

If there's any insight on what i could try, i'd appreciate it. thank you!

**Comment by liamwhite** [comment]
Not sure, but try adding this to .cargo/config (if it doesn't exist, create it)
```toml
[net]
retry = 2                   # network retries
git-fetch-with-cli = true   # use the `git` executable for git
```
