### ISSUE TITLE
"Could not fetch environment variable "PORT" because it is not set."

### ISSUE THREAD

**Issue by KamillaPup** [philomena-dev/philomena#224]
I've had to move to a new server and switched to prod mode but the first step was to build a virgin philomena from the latest version then move data over.

Sadly, I keep getting this error when doing docker-compose up
```
app_1            | 19:41:41.167 [info] Loading 141 CA(s) from :otp store
app_1            | ** (System.EnvError) could not fetch environment variable "PORT" because it is not set
app_1            |     (elixir 1.16.1) lib/system.ex:721: System.fetch_env!/1
app_1            |     /srv/philomena/config/runtime.exs:133: (file)
app_1            |     (stdlib 5.2) erl_eval.erl:750: :erl_eval.do_apply/7
app_1            |     (stdlib 5.2) erl_eval.erl:1026: :erl_eval.expr_list/7
app_1            |     (stdlib 5.2) erl_eval.erl:292: :erl_eval.expr/6
app_1            |     (stdlib 5.2) erl_eval.erl:282: :erl_eval.expr/6
app_1            |     (stdlib 5.2) erl_eval.erl:283: :erl_eval.expr/6
app_1            | 
app_1            | 19:41:41.184 [info] Loading 141 CA(s) from :otp store
app_1            | ** (System.EnvError) could not fetch environment variable "PORT" because it is not set
app_1            |     (elixir 1.16.1) lib/system.ex:721: System.fetch_env!/1
app_1            |     /srv/philomena/config/runtime.exs:133: (file)
app_1            |     (stdlib 5.2) erl_eval.erl:750: :erl_eval.do_apply/7
app_1            |     (stdlib 5.2) erl_eval.erl:1026: :erl_eval.expr_list/7
app_1            |     (stdlib 5.2) erl_eval.erl:292: :erl_eval.expr/6
app_1            |     (stdlib 5.2) erl_eval.erl:282: :erl_eval.expr/6
app_1            |     (stdlib 5.2) erl_eval.erl:283: :erl_eval.expr/6
```
I'm not sure how it's not set? I'm including my docker-compose.yml with salts and private info redacted.
```
version: '3'
volumes:
  postgres_data: {}
  elastic_data: {}

services:
  app:
    build:
      context: .
      dockerfile: ./docker/app/Dockerfile
    environment:
      - MIX_ENV=prod
      - PGPASSWORD=postgres
      - ANONYMOUS_NAME_SALT=*redacted*
      - HCAPTCHA_SECRET_KEY=*redacted*
      - HCAPTCHA_SITE_KEY=*redacted*
      - PASSWORD_PEPPER=*redacted*
      - TUMBLR_API_KEY=*redacted*
      - OTP_SECRET_KEY=*redacted*
      - ADVERT_FILE_ROOT=adverts
      - AVATAR_FILE_ROOT=avatars
      - BADGE_FILE_ROOT=badges
      - IMAGE_FILE_ROOT=images
      - TAG_FILE_ROOT=tags
      - AVATAR_URL_ROOT=/avatars
      - ADVERT_URL_ROOT=/spns
      - IMAGE_URL_ROOT=/img
      - BADGE_URL_ROOT=/badge-img
      - TAG_URL_ROOT=/tag-img
      - ELASTICSEARCH_URL=http://elasticsearch:9200
      - REDIS_HOST=redis
      - DATABASE_URL=ecto://postgres:postgres@postgres/philomena_dev
      - CDN_HOST=localhost
      - MAILER_ADDRESS=*redacted*
      - START_ENDPOINT=true
      - SITE_DOMAINS=*redacted*
      - S3_SCHEME=http
      - S3_HOST=files
      - S3_PORT=80
      - S3_BUCKET=philomena
      - AWS_ACCESS_KEY_ID=local-identity
      - AWS_SECRET_ACCESS_KEY=local-credential
      - SMTP_DOMAIN=*redacted*
      - SMTP_USERNAME=*redacted*
      - SMTP_PASSWORD=*redacted*
      - SMTP_PORT=587
      - SMTP_RELAY=*redacted*
    working_dir: /srv/philomena
    tty: true
    volumes:
      - .:/srv/philomena
    depends_on:
      - postgres
      - elasticsearch
      - redis

  postgres:
    image: postgres:16.2-alpine
    environment:
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    logging:
      driver: "none"

  elasticsearch:
    image: elasticsearch:7.9.3
    volumes:
      - elastic_data:/usr/share/elasticsearch/data
    logging:
      driver: "none"
    environment:
      - discovery.type=single-node
    ulimits:
      nofile:
        soft: 65536
        hard: 65536

  redis:
    image: redis:7.2.4-alpine
    logging:
      driver: "none"

  files:
    image: andrewgaul/s3proxy:sha-ec12ae0
    environment:
      - JCLOUDS_FILESYSTEM_BASEDIR=/srv/philomena/priv/s3
    volumes:
      - .:/srv/philomena

  web:
    build:
      context: .
      dockerfile: ./docker/web/Dockerfile
      args:
        - APP_DIR=/srv/philomena
        - S3_SCHEME=http
        - S3_HOST=files
        - S3_PORT=80
        - S3_BUCKET=philomena
    volumes:
      - .:/srv/philomena
    environment:
      - AWS_ACCESS_KEY_ID=local-identity
      - AWS_SECRET_ACCESS_KEY=local-credential
    logging:
      driver: "none"
    depends_on:
      - app
    ports:
      - '8080:80'
```

Later on, I need to migrate the existing thumbs and database to this install and not sure how to do that. Ideally, I'd like to host all posts on Wasabi... also no clue lol.
